apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment3
  labels:
    app: new-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: new-web  # Must match the Pod template labels
  template:
    metadata:
      labels:
        app: new-web # Must match the deployment's selector
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80