apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: 0ld-web  # This service selects Pods with the label app: 0ld-web
  ports:
    - protocol: TCP
      port: 80        # The port exposed within the cluster
      targetPort: 80   # The port the container listens on
  type: ClusterIP      # Default type, exposes service internally within the cluster

