apiVersion: v1
kind: Pod
metadata:
  name: pod-using-pvc
spec:
  containers:
  - name: my-container
    image: busybox
    command: ['sh', '-c', 'while true; do sleep 3600; done']  # Keeps the pod running
    volumeMounts:
    - name: pvc-volume
      mountPath: /mnt/data  # The directory where the PVC will be mounted in the container
  volumes:
  - name: pvc-volume
    persistentVolumeClaim:
      claimName: my-pvc  # Reference to the existing PVC