apiVersion: v1
kind: Pod
metadata:
  name: subpath-pod
spec:
  containers:
  - name: my-container
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
    volumeMounts:
    - name: my-volume
      mountPath: /app/config
      subPath: config     # Subdirectory inside the volume
    - name: my-volume
      mountPath: /app/logs
      subPath: logs       # Another subdirectory inside the same volume
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: my-pvc2