apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
spec:
  containers:
  - name: writer
    image: busybox
    command: ["/bin/sh", "-c", "echo 'Hello from the writer container!' > /mnt/volume/shared-data.txt && sleep 3600"]
    volumeMounts:
    - name: shared-volume
      mountPath: /mnt/volume
  - name: reader
    image: busybox
    command: ["/bin/sh", "-c", "cat /mnt/volume/shared-data.txt && sleep 3600"]
    volumeMounts:
    - name: shared-volume
      mountPath: /mnt/volume
  volumes:
  - name: shared-volume
    emptyDir: {}