apiVersion: v1
kind: Pod
metadata:
  name: git-repo-pod
spec:
  containers:
  - name: my-container
    image: alpine/git
    command: ['sh', '-c', 'while true; do sleep 3600; done']
    volumeMounts:
    - name: git-repo-volume
      mountPath: /data/git
  volumes:
  - name: git-repo-volume
    gitRepo:
      repository: https://github.com/halimo22/Lab5
      revision: main  # Branch or commit SHA to checkout
