apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 5Gi  # Size of the volume
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc  # Use your StorageClass name here
  awsElasticBlockStore:
    volumeID: vol-xxxxxxxx  # Replace with your EBS volume ID
    fsType: ext4             # File system type (e.g., ext4, xfs)
