apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restricted-pod-access
  namespace: my-namespace
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]  
- apiGroups: ["apps"]  
  resources: ["deployments"]
  verbs: ["get", "list"]