apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-manager
  namespace: dev  # Specify the namespace where the permissions apply
rules:
- apiGroups: ["apps"]  # API group for deployments
  resources: ["deployments"]
  verbs: ["create", "update", "delete"]