apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: persistent-volume-access
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["PersistentVolumeClaims"]
  verbs: ["create", "delete"]